[build]
  publish = "build"
  command = "npx tailwindcss -i ./src/input.css -o ./build/css//gen/output.css --minify" # Only needed if you need to build TailwindCSS

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true